<a href="https://colab.research.google.com/github/Shruti-Raj-Vansh-Singh/PyTorch-Tutorial/blob/master/PyTorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import print_function
import torch

Matrix with unitialized values. \
since we didinot initialize any values, we will get garbage value

In [3]:
#empty matrix which shows values stored at the memory location
matrix = torch.empty(5,3)
print(matrix)

tensor([[8.0635e-36, 0.0000e+00, 1.6956e-43],
        [5.6052e-44, 1.4714e-43, 1.6255e-43],
        [1.4153e-43, 1.5975e-43, 1.3593e-43],
        [1.3733e-43, 1.5134e-43, 1.4153e-43],
        [5.7453e-44, 2.2856e+20, 5.0948e-14]])


In [5]:
#randomly initialize the matrix
x = torch.rand(5,3)
print(x)

tensor([[0.3980, 0.2450, 0.6724],
        [0.3450, 0.9107, 0.4150],
        [0.1789, 0.9120, 0.6980],
        [0.2695, 0.2280, 0.8511],
        [0.7981, 0.7413, 0.5560]])


In [6]:
#a matrix of zeros and of datatype long
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
#constructing qa tensor drectly from data ie, initializing an array
x = torch.tensor([3.6,9])
print(x)

tensor([3.6000, 9.0000])


Building new tensors using existing tensors

In [12]:
# new_* methods takes as input the size
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [15]:
#override datatype
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.3857, 0.6710, 0.3176],
        [0.9357, 0.5033, 0.8439],
        [0.7243, 0.5704, 0.5183],
        [0.5346, 0.5955, 0.2558],
        [0.8766, 0.3197, 0.5410]])


Function to get the size of tensor

In [16]:
print(x.size())

torch.Size([5, 3])


## OPERATIONS

Addition of 2 matrices

In [18]:
y = torch.rand(5,3)
#sytnax 1
print(x+y)

#syntax 2
print(torch.add(x,y))

tensor([[0.6781, 0.8435, 1.1490],
        [1.8821, 1.4147, 1.6446],
        [1.3075, 1.4784, 1.2214],
        [1.1190, 1.4616, 0.3947],
        [1.4692, 0.5730, 0.6178]])
tensor([[0.6781, 0.8435, 1.1490],
        [1.8821, 1.4147, 1.6446],
        [1.3075, 1.4784, 1.2214],
        [1.1190, 1.4616, 0.3947],
        [1.4692, 0.5730, 0.6178]])


In [19]:
#provide an output tensor
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[0.6781, 0.8435, 1.1490],
        [1.8821, 1.4147, 1.6446],
        [1.3075, 1.4784, 1.2214],
        [1.1190, 1.4616, 0.3947],
        [1.4692, 0.5730, 0.6178]])


In [20]:
#addition in place ie, add x to y
y.add(x)
print(y)

tensor([[0.2924, 0.1725, 0.8314],
        [0.9464, 0.9114, 0.8008],
        [0.5833, 0.9080, 0.7031],
        [0.5844, 0.8661, 0.1389],
        [0.5926, 0.2533, 0.0767]])


Printing similar like in numpy

In [21]:
print(x[:,1])

tensor([0.6710, 0.5033, 0.5704, 0.5955, 0.3197])


Resize the tensor

In [22]:
#resize/reshape tensor
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)  #the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


Single element tensor \
to print the value of that single element as a python number we use x.item()

In [24]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.9543])
0.9542859196662903


## Numpy Bridge
converting pytorch tensor to numpy array and vice versa

Convertinf tensor to array



In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


this is possible as the memory location of both the tensor and numpy array is same on CPU

In [27]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


converting array to numpy \
all tensor on CPU expect char is supported

In [28]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
np.add(a,1,out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA tensors
tensors can be moved to any device using .to method \
this will work only if we have cuda on the device

In [30]:
if torch.cuda.is_available():
  device = torch.device("cuda")                      #a cuda device object   
  y = torch.ones_like(x, device=device)              # directly using the tensor on GPU
  x = x.to(device)                                   # using method to(device_name)
  z = x+y
  print(z)
  print(z.to("cpu", torch.double))