<a href="https://colab.research.google.com/github/Shruti-Raj-Vansh-Singh/PyTorch-Tutorial/blob/master/PyTorch_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AUTOGRAD
It provides automatic differentiation for all operations on Tensors. \
It is a** define-and-run framework** which means that the backprop defined by how we code is run and that every single iteration can be different 

In [1]:
import torch

In [3]:
#creating a tensor with require_grad=true so that we can track the computations within
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
#tensor operation
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


grad_fn refers a function that has created the tensor.

In [6]:
#since y was created as an operation function for x, it has a grad_fn
print(y.grad_fn)

In [7]:
z = y*y*3
out = y.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(3., grad_fn=<MeanBackward0>)


.requires_grad_() changes an existing tensor's requires_grad flag in-place. The input flag defaults to False.

In [9]:
a = torch.rand(2,2)
a = ((a-3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b =  (a*a).sum()
print(b.grad_fn)

False
True


# GRADIENTS
backprop \
since out is a single tensor we can directly write out.backward() instead of out.backward(torch.tensor(1.))

In [10]:
out.backward()

In [11]:
#printing the gradient
print(x.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


Generally speaking, torch.autograd is an engine for computing vector-Jacobian product.

In [13]:
x = torch.rand(3, requires_grad=True)
y = x*3
while y.data.norm() <1000:
  y=y*2
print(y)

tensor([ 318.8128,  135.3183, 1363.8234], grad_fn=<MulBackward0>)


in this case y is no longer a scalar. hence torch.autograd cannot compute the full jacobin directly, but if we want the vector jacobian prodeuct we simply need to pass backward to y


In [14]:
v = torch.tensor([0.1,1.0,0.0001], dtype = float)
y.backward(v)
print(x.grad)

tensor([1.5360e+02, 1.5360e+03, 1.5360e-01])


if we dont want autograd to keep a track of the history we can use either of the two methods: \
1. wrapping the code block in with torch.no_grad()
2. using .detach() to get a new tensor with same content but no gradient

In [15]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
  print((x**2).requires_grad)


True
True
False


In [16]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
